name: MineFight
version: 0.3.6
description:
author: Tobias Schramm 'Toble_Miner'
website:
softdepend: [Vault,PermissionsEx,ProtocolLib]

main: TobleMiner.MineFight.Main

commands:
   mpvp:
      description: Controlcommand for MineFight
      usage: /mpvp [additional arguments]

permissions:
